### ISSUE TITLE
Log Console UI - 502 nginx error after upgrading to 4.3.30 helm chart

### ISSUE THREAD

**Issue by eilonash92** [jenkinsci/helm-charts#896]
### Describe the bug

Hi,

Getting this error when using unknown method -

```Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 8bd191bf-b05d-4a1a-a7db-16bbeed8f4ad
java.lang.NoSuchMethodError: No such DSL method 'blabla' found among steps [addBadge, addErrorBadge, addHtmlBadge, addInfoBadge, addShortText, addWarningBadge, ansiColor, archive, bat, build, catchError, checkout, compareVersions, container, containerLog, createSummary, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, 
```

However my main issue is - when I refresh the page I receive 502 nginx error, and I can't see the logs in the UI anymore.

Is it a common bug in this version? did you fix it? is it related to the CPS plugin?

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.3.30

### What happened?

```bash
1.
2.
3.
...
```
